version: '3.8'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    ports:
      - "5432:5432"
    volumes:
      - mlm_postgres-data:/var/lib/postgresql/data/

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 mlm.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mlm_postgres-data:

